- SetCronJob
- AppEngine-Google
- Bad-Neighborhood
- Baiduspider
- bitlybot
- Bitacoras.com
- buzzzy.com
- curl
- CoralWebPrx
- Digg URI Canonicalizer
- rtweetme
- facebookexternalhit
- GingerCrawler
- gooblog
- GurujiBot
- hitcrawler
- twubs.com
- ia_archiver
- investigate-tweet
- kame-rt
- JS-Kit URL Resolver
- justsignal
- larbin
- libwww-perl
- Link Checker
- LongURL API
- LWP::Simple
- Mediapartners-Google
- MetaURI API
- Microsoft URL Control
- Feedsky crawler
- MLBot
- TrendAI.com
- http://www.80legs.com/spider.html
- http://www.ellerdale.com/crawler.html
- http://labs.topsy.com/butterfly.html
- Evrinid-RT
- Feedtrace-bot
- FriendFeedBot
- Googlebot
- HiveCrawler
- huffingtonpost.com
- InfuzApp
- MJ12bot
- mxbot
- page-store
- Rivva
- ScoutJet
- Semiocast HTTP client
- ShortLinkTranslate
- spbot
- Tweetmi
- Twingly Recon
- http://twitturls.com
- VH Bot
- VideoSurf_bot
- woriobot
- Yahoo! Slurp
- Feedfetcher-Google
- FauBot
- Twiceler
- msnbot
- my6sense
- PostRank
- PycURL
- Python-httplib
- Python-urllib
- R6_FeedFetcher
- radian6_default_
- radian6_linkcheck_
- ShareThisFetch
- Snapbot
- Sogou web spider
- Sosospider
- Speedy Spider
- StatusNet
- Surphace Scout
- tagcloude
- tagesthemadev
- Tasapspider
- ThingFetcher
- http://www.tumblr.com
- Twingly Recon
- Twitturly
- Voyager
- web18bot
- Wget
- Y!J-BRO/YFSJ crawler
- Y!J-BSC/1.0
- yacybot
- Yeti
- Yandex
- ytndemo
- Zend_Http_Client
- kmbot
- OneRiot
- Windows-Live-Social-Object-Extractor-Engine
- Twitterbot
- twitmatic
- bingbot
- Python-httplib2
- Crowsnest
- AsyncHttpClient
- http://flipboard.com/browserproxy
- http://www.bsalsa.com
- QQDownload
- Java/