
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: recipela_dev
  username: root
  password: 

test:
  <<: *default
  database: recipela_test
  username: root
  password:
