home: &home
  page_title: "RecipeLa"
  meta_title: "RecipeLa"
  meta_description: "RecipeLa is the ultimate cooking social community, where recipes come to life. Wanna know what you will gain by joining us? You will win awesome prizes, make new friends and share delicious recipes."
  og_title: "RecipeLa"
  og_description: "RecipeLa is the ultimate cooking social community, where recipes come to life. Wanna know what you will gain by joining us? You will win awesome prizes, make new friends and share delicious recipes."