home: &home
  page_title: "RecipeLa | Cooking Social Community"
  meta_title: "RecipeLa | Cooking Social Community"
  meta_description: "RecipeLa is the ultimate cooking social community, where recipes come to life. Wanna know what you will gain by joining us? You will win awesome prizes, make new friends and share delicious recipes."
  og_title: "RecipeLa | Cooking Social Community"
  og_description: "RecipeLa is the ultimate cooking social community, where recipes come to life. Wanna know what you will gain by joining us? You will win awesome prizes, make new friends and share delicious recipes."
recipes: &recipes
  page_title: "RecipeLa | Cooking Social Community"
  meta_title: "RecipeLa | Cooking Social Community"
  meta_description: "RecipeLa is the ultimate cooking social community, where recipes come to life. Wanna know what you will gain by joining us? You will win awesome prizes, make new friends and share delicious recipes."
  og_title: "RecipeLa | Cooking Social Community"
  og_description: "RecipeLa is the ultimate cooking social community, where recipes come to life. Wanna know what you will gain by joining us? You will win awesome prizes, make new friends and share delicious recipes."